### PR TITLE
Habit and resource error handling

### PR DESCRIPTION
**Pull request by rubybfm1017**

### CODE REVIEW

**Comment by JamesKoenig** [comment]
the habit errors should be rendered on the habit form and not the habit show component

**Comment by rubybfm1017** [comment]
> the habit errors should be rendered on the habit form and not the habit show component

**Comment by rubybfm1017** [comment]
> the habit errors should be rendered on the habit form and not the habit show component

Rendering on habit form is easier and looks better

**Comment by rubybfm1017** [comment]
> the habit errors should be rendered on the habit form and not the habit show component

changed to render under forms

**Review by JamesKoenig — APPROVED** [review]

**Pull request merged**
